define(["jquery","cookie"],function($){
	$.ajax({
		type:'get',
		url:"/html/include/header.html",
		success:function(data){
			console.log(data);
			var _username = $.cookie("loginUser");
			if(_username){//存在登录成功的用户
				$(data).filter(".login")
					.html(_username).end()
					.appendTo(".head");
			}else{
				$(data).appendTo(".head");
			}
		}
	})
	$.ajax({
		type:'get',
		url:"/html/include/footer.html",
		success:function(data){
			$(data).appendTo(".footer");
		}
	})
});
